name: ML CI/CD Pipeline (multi-job)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/


  train:
    runs-on: ubuntu-latest
    needs: test   # 👈 Este job solo se ejecuta si "test" termina con éxito
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model.pkl

  deploy:
    runs-on: ubuntu-latest
    needs: train  # 👈 Solo se ejecuta si "train" terminó correctamente
    steps:
      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model

      - name: Build Docker image
        run: |
          docker build -t ml-model-api .
          docker images

      - name: Run container test
        run: |
          docker run -d -p 8000:8000 ml-model-api
          sleep 5
          curl -f http://localhost:8000/
